// Generated by CoffeeScript 1.6.2
(function() {
  var go_backwards, go_forwards, navigation_enabled;

  navigation_enabled = true;

  go_backwards = function() {
    if (navigation_enabled) {
      return console.log("go backwards");
    }
  };

  go_forwards = function() {
    if (navigation_enabled) {
      return console.log("go forwards");
    }
  };

  $("#submit-something").get(0).onclick = function() {
    $("#submit-dialog").show();
    return navigation_enabled = false;
  };

  $("#chicken-out").get(0).onclick = function() {
    $("#submit-dialog").hide();
    return navigation_enabled = true;
  };

  $("#submit-slander").get(0).onclick = function() {
    $.ajax({
      url: "/submit",
      dataType: "json",
      data: {
        message: $("#slander-message").val(),
        image: $("#slander-image").val()
      },
      type: "POST"
    }).done(function(resp) {
      return console.dir(resp);
    }).fail(function(jqXHR, e_status, e_thrown) {
      alert("something went wrong. anarchy not possible at this moment.");
      console.log(e_status);
      return console.log(e_thrown);
    });
    console.log("submitted message: " + $("#slander-message").val());
    console.log("submitted image: " + $("#slander-image").val());
    $("#slander-message").val("");
    $("#slander-image").val("");
    $("#submit-dialog").hide();
    return navigation_enabled = true;
  };

  $(document).on("keyup", null, "left", function() {
    return go_backwards();
  });

  $(document).on("keyup", null, "a", function() {
    return go_backwards();
  });

  $(document).on("keyup", null, "right", function() {
    return go_forwards();
  });

  $(document).on("keyup", null, "d", function() {
    return go_forwards();
  });

}).call(this);
