// Generated by CoffeeScript 1.6.2
(function() {
  var director, http, router, server, submit_slander, used_get;

  http = require("http");

  director = require("director");

  used_get = function() {
    this.res.writeHead(404, {
      "Content-Type": "text/plain",
      "charset": "utf8"
    });
    return this.res.end("invalid request");
  };

  submit_slander = function() {
    this.res.writeHead(200, {
      "Content-Type": "application/json",
      "charset": "utf8"
    });
    if (!this.req.body) {
      this.res.end(JSON.stringify({
        error: "error"
      }));
      return;
    }
    return this.res.end(JSON.stringify(this.req.body));
  };

  router = new director.http.Router({
    '/submit': {
      get: used_get,
      post: submit_slander
    }
  });

  server = http.createServer(function(req, res) {
    req.chunks = [];
    req.on("data", function(chunk) {
      return req.chunks.push(chunk.toString());
    });
    return router.dispatch(req, res, function(err) {
      if (err) {
        res.writeHead(404);
        return res.end();
      }
    });
  });

  server.listen(5666);

}).call(this);
