// Generated by CoffeeScript 1.6.2
(function() {
  var Messages, Sequelize, admin_password, director, htmlencode, http, retrieve_pending_slander, retrieve_slander, router, server, sql, submit_pending_slander, submit_slander, url;

  http = require("http");

  url = require("url");

  director = require("director");

  Sequelize = require("sequelize");

  htmlencode = require("htmlencode");

  admin_password = "12345";

  htmlencode.EncodeType = "numerical";

  sql = new Sequelize("prattorgfree", "postgres", "12345", {
    host: "localhost",
    port: 5432,
    dialect: "postgres",
    define: {
      underscored: true
    },
    logging: false
  });

  Messages = sql.define("messages", {
    message: {
      allowNull: false,
      type: Sequelize.TEXT,
      validate: {
        notEmpty: true
      }
    },
    image: {
      defaultValue: "",
      allowNull: false,
      type: Sequelize.TEXT,
      validate: {
        isUrl: true
      }
    },
    approved: {
      allowNull: false,
      type: Sequelize.BOOLEAN,
      defaultValue: false
    }
  }, {
    paranoid: false,
    underscored: true
  });

  submit_slander = function() {
    var res;

    res = this.res;
    res.writeHead(200, {
      "Content-Type": "application/json",
      "charset": "utf8"
    });
    if (!this.req.body.message || (this.req.body.message == null)) {
      return res.end(JSON.stringify({
        error: "invalid request, no slander message."
      }));
    }
    if (this.req.body.image && (this.req.body.image != null)) {
      if (!this.req.body.image.match("(http|https):\/\/i\.imgur\.com\/([a-zA-Z0-9]+)\.(jpg|jpeg|png|gif)")) {
        return res.end(JSON.stringify({
          error: "invalid request, invalid imgur url."
        }));
      }
    } else {
      this.req.body.image = "";
    }
    return Messages.create({
      message: htmlencode.htmlEncode(this.req.body.message),
      image: this.req.body.image
    }).success(function() {
      return res.end(JSON.stringify({
        success: "you've made simon sad. congratulations."
      }));
    }).error(function(e) {
      return res.end(JSON.stringify({
        error: "welp. there was a database error. you should try to submit your message again in a few minutes."
      }));
    });
  };

  retrieve_slander = function() {
    var res;

    res = this.res;
    res.writeHead(200, {
      "Content-Type": "text/plain",
      "charset": "utf8"
    });
    return sql.query("SELECT message, image FROM messages WHERE approved = true ORDER BY RANDOM() LIMIT 1").success(function(result) {
      if (result.length > 0) {
        return res.end(JSON.stringify({
          message: result[0].message,
          image: result[0].image
        }));
      } else {
        return res.end(JSON.stringify({
          error: "no more content."
        }));
      }
    }).error(function() {
      return res.end(JSON.stringify({
        error: "no more content."
      }));
    });
  };

  retrieve_pending_slander = function() {
    var password, res;

    res = this.res;
    res.writeHead(200, {
      "Content-Type": "text/plain",
      "charset": "utf8"
    });
    password = url.parse(this.req.url, true).query.password;
    if (!(password === admin_password)) {
      return res.end(JSON.stringify({
        error: "invalid password."
      }));
    }
    return Messages.findAll({
      where: {
        approved: false
      },
      limit: 10
    }).success(function(messages) {
      return res.end(JSON.stringify({
        messages: messages
      }));
    }).error(function() {
      return res.end(JSON.stringify({
        error: "no more content."
      }));
    });
  };

  submit_pending_slander = function() {
    var res;

    res = this.res;
    res.writeHead(200, {
      "Content-Type": "application/json",
      "charset": "utf8"
    });
    if (!(this.req.body.password === admin_password)) {
      return res.end(JSON.stringify({
        error: "invalid password."
      }));
    }
    if (!this.req.body.action || (this.req.body.action == null)) {
      return res.end(JSON.stringify({
        error: "inalid request, select an action."
      }));
    }
    if (!this.req.body.id.match("([0-9]+)")) {
      return res.end(JSON.stringify({
        error: "invalid message id."
      }));
    }
    if (this.req.body.action === "accept") {
      return sql.query("UPDATE messages SET approved = true WHERE id = " + this.req.body.id).success(function() {
        return res.end(JSON.stringify({
          success: "accepted that message."
        }));
      }).error(function() {
        return res.end(JSON.stringify({
          error: "could not accept that message."
        }));
      });
    } else if (this.req.body.action === "delete") {
      return sql.query("DELETE FROM messages WHERE id = " + this.req.body.id).success(function() {
        return res.end(JSON.stringify({
          success: "deleted that message."
        }));
      }).error(function() {
        return res.end(JSON.stringify({
          error: "could not delete that message."
        }));
      });
    } else {
      return res.end(JSON.stringify({
        error: "woah, you can't just make up new actions."
      }));
    }
  };

  router = new director.http.Router({
    '/back/submit': {
      post: submit_slander
    },
    '/back/retrieve': {
      get: retrieve_slander
    },
    '/back/admin': {
      get: retrieve_pending_slander,
      post: submit_pending_slander
    }
  });

  server = http.createServer(function(req, res) {
    req.chunks = [];
    req.on("data", function(chunk) {
      return req.chunks.push(chunk.toString());
    });
    return router.dispatch(req, res, function(err) {
      if (err) {
        res.writeHead(404);
        return res.end();
      }
    });
  });

  Messages.sync().success(function() {
    return server.listen(5666);
  }).failure(function(e) {
    return console.log(e);
  });

}).call(this);
